### ISSUE TITLE
ypeError: storageSession.getItem is not a function

### ISSUE THREAD

**Issue by Li-designer** [xiaoxian521/electron-pure-admin#1]
vue-router.mjs:3451 TypeError: storageSession.getItem is not a function
![Xnip2023-01-17_19-44-43](https://user-images.githubusercontent.com/76248405/212890717-29f68a17-ba4c-4aa5-95af-bfee594ecc23.jpg)

**Comment by xiaoxian521** [comment]
你的代码很早拉的吧 升级最新版
